const recipes = [
  {
    id: "1",
    title: "Spicy Thai Basil Noodles",
    description:
      "Bold, fiery rice noodles tossed with fresh Thai basil, garlic, and a savory-sweet sauce. Ready in under 30 minutes and packed with Southeast Asian flavors.",
    image:
      "https://images.unsplash.com/photo-1707546944460-dda9069b9c1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aGFpJTIwbm9vZGxlcyUyMHJlc3RhdXJhbnQlMjBwbGF0ZXxlbnwxfHx8fDE3NzMwMzYzNDF8MA&ixlib=rb-4.1.0&q=80&w=1080",
    time: "25 min",
    cost: "$8",
    servings: 2,
    category: "Asian",
    tag: "Spicy",
    ingredients: [
      { name: "Flat rice noodles", amount: "200g" },
      { name: "Ground pork or chicken", amount: "150g" },
      { name: "Fresh Thai basil leaves", amount: "1 cup" },
      { name: "Garlic cloves, minced", amount: "4 cloves" },
      { name: "Red chili, sliced", amount: "2 chilies" },
      { name: "Soy sauce", amount: "2 tbsp" },
      { name: "Oyster sauce", amount: "1 tbsp" },
      { name: "Fish sauce", amount: "1 tsp" },
      { name: "Sugar", amount: "1 tsp" },
      { name: "Vegetable oil", amount: "2 tbsp" },
    ],
    steps: [
      "Soak rice noodles in hot water for 8 minutes until pliable, then drain and set aside.",
      "Heat oil in a wok over high heat until smoking. Add garlic and chili, stir-fry for 30 seconds until fragrant.",
      "Add ground meat, breaking it apart with a spatula, and cook for 3–4 minutes until browned.",
      "Push meat to the side, add noodles, and pour in soy sauce, oyster sauce, fish sauce, and sugar. Toss everything together over high heat for 2 minutes.",
      "Remove from heat, fold in fresh Thai basil leaves, and toss until just wilted.",
      "Plate immediately and serve with a wedge of lime and extra sliced chili on the side.",
    ],
    nutrition: {
      calories: 520,
      protein: "28g",
      carbs: "62g",
      fat: "14g",
    },
  },
  {
    id: "2",
    title: "Creamy Vegetable Korma",
    description:
      "A rich, mildly spiced Indian curry with tender vegetables simmered in a cashew-coconut cream sauce. Aromatic and deeply satisfying without any heat.",
    image:
      "https://images.unsplash.com/photo-1729824159986-376b49c6b7e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjdXJyeSUyMGRpc2glMjBmb29kJTIwcGhvdG9ncmFwaHl8ZW58MXx8fHwxNzczMDM2MzQxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    time: "30 min",
    cost: "$10",
    servings: 3,
    category: "Indian",
    tag: "Creamy",
    ingredients: [
      { name: "Potatoes, cubed", amount: "2 medium" },
      { name: "Carrots, sliced", amount: "2 carrots" },
      { name: "Green peas", amount: "½ cup" },
      { name: "Onion, finely diced", amount: "1 large" },
      { name: "Garlic cloves, minced", amount: "3 cloves" },
      { name: "Fresh ginger, grated", amount: "1 tsp" },
      { name: "Coconut milk", amount: "1 can (400ml)" },
      { name: "Cashews, soaked 10 min", amount: "¼ cup" },
      { name: "Korma paste or curry powder", amount: "2 tbsp" },
      { name: "Vegetable oil", amount: "2 tbsp" },
      { name: "Salt", amount: "to taste" },
    ],
    steps: [
      "Blend soaked cashews with ¼ cup of water until completely smooth; set aside.",
      "Heat oil in a deep pan over medium heat. Sauté onion for 5 minutes until golden, then add garlic and ginger for 1 more minute.",
      "Add korma paste and stir constantly for 1 minute until aromatic.",
      "Add potatoes and carrots, stir to coat with the paste, then pour in coconut milk and bring to a simmer.",
      "Cover and cook on medium-low for 15 minutes until vegetables are fork-tender.",
      "Stir in cashew cream and green peas. Simmer uncovered for 3 more minutes until sauce thickens slightly. Season with salt.",
      "Serve over steamed basmati rice, garnished with fresh cilantro.",
    ],
    nutrition: {
      calories: 410,
      protein: "9g",
      carbs: "48g",
      fat: "22g",
    },
  },
  {
    id: "3",
    title: "Teriyaki Chicken Rice Bowl",
    description:
      "Juicy pan-seared chicken glazed with a homemade teriyaki sauce served over fluffy Japanese short-grain rice. Sweet, salty, and completely addictive.",
    image:
      "https://images.unsplash.com/photo-1664717698774-84f62382613b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHJpY2UlMjBib3dsJTIwcmVjaXBlfGVufDF8fHx8MTc3MzAzNjM0MHww&ixlib=rb-4.1.0&q=80&w=1080",
    time: "20 min",
    cost: "$7",
    servings: 2,
    category: "Japanese",
    tag: "Savory",
    ingredients: [
      { name: "Chicken thighs, boneless", amount: "2 pieces (300g)" },
      { name: "Soy sauce", amount: "3 tbsp" },
      { name: "Mirin", amount: "2 tbsp" },
      { name: "Honey", amount: "1 tbsp" },
      { name: "Garlic cloves, minced", amount: "2 cloves" },
      { name: "Sesame oil", amount: "1 tsp" },
      { name: "Cooked Japanese rice", amount: "2 cups" },
      { name: "Green onions, sliced", amount: "2 stalks" },
      { name: "Sesame seeds", amount: "1 tsp" },
      { name: "Vegetable oil", amount: "1 tbsp" },
    ],
    steps: [
      "Mix soy sauce, mirin, honey, garlic, and sesame oil in a small bowl to make the teriyaki sauce.",
      "Pat chicken thighs dry with paper towels and season lightly with salt.",
      "Heat vegetable oil in a skillet over medium-high heat. Place chicken skin-side down and cook for 5 minutes until golden and crispy.",
      "Flip chicken and cook the other side for 4 minutes, then pour in teriyaki sauce.",
      "Reduce heat to medium and spoon sauce over chicken continuously for 2–3 minutes until sauce thickens and coats the chicken.",
      "Slice chicken and serve over warm rice. Drizzle remaining sauce over the top, then garnish with green onions and sesame seeds.",
    ],
    nutrition: {
      calories: 580,
      protein: "38g",
      carbs: "65g",
      fat: "16g",
    },
  },
  {
    id: "4",
    title: "Garlic Butter Shrimp Stir-Fry",
    description:
      "Plump shrimp and crisp vegetables tossed in a rich garlic butter sauce with a hint of soy and lemon. A restaurant-quality dish done in under 20 minutes.",
    image:
      "https://images.unsplash.com/photo-1761314025701-34795be5f737?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGlyJTIwZnJ5JTIwdmVnZXRhYmxlcyUyMGRpbm5lcnxlbnwxfHx8fDE3NzMwMzYzNDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    time: "15 min",
    cost: "$6",
    servings: 2,
    category: "Seafood",
    tag: "Buttery",
    ingredients: [
      { name: "Medium shrimp, peeled and deveined", amount: "250g" },
      { name: "Broccoli florets", amount: "1 cup" },
      { name: "Bell pepper, sliced", amount: "1 pepper" },
      { name: "Garlic cloves, minced", amount: "5 cloves" },
      { name: "Unsalted butter", amount: "3 tbsp" },
      { name: "Soy sauce", amount: "1 tbsp" },
      { name: "Lemon juice", amount: "1 tbsp" },
      { name: "Red pepper flakes", amount: "¼ tsp" },
      { name: "Salt and black pepper", amount: "to taste" },
      { name: "Fresh parsley, chopped", amount: "2 tbsp" },
    ],
    steps: [
      "Pat shrimp completely dry and season with salt, black pepper, and red pepper flakes.",
      "Melt 1 tbsp butter in a large skillet over high heat. Add broccoli and bell pepper; stir-fry for 3 minutes until slightly charred but still crisp. Remove and set aside.",
      "In the same pan, melt remaining butter over medium-high heat. Add garlic and cook for 30 seconds until golden and fragrant.",
      "Add shrimp in a single layer and cook for 90 seconds per side until pink and curled.",
      "Return vegetables to the pan, add soy sauce and lemon juice, and toss everything together for 1 minute.",
      "Remove from heat, sprinkle with fresh parsley, and serve immediately over rice or with crusty bread.",
    ],
    nutrition: {
      calories: 320,
      protein: "32g",
      carbs: "12g",
      fat: "17g",
    },
  },
  {
    id: "5",
    title: "Spaghetti Carbonara",
    description:
      "A classic Roman pasta made with silky eggs, aged Pecorino, crispy pancetta, and plenty of cracked black pepper. No cream — just pure technique.",
    image:
      "https://images.unsplash.com/photo-1676300184847-4ee4030409c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZWFsdGh5JTIwcGFzdGElMjBkaXNoJTIwbWVhbHxlbnwxfHx8fDE3NzMwMzYzNDB8MA&ixlib=rb-4.1.0&q=80&w=1080",
    time: "20 min",
    cost: "$9",
    servings: 3,
    category: "Italian",
    tag: "Hearty",
    ingredients: [
      { name: "Spaghetti", amount: "300g" },
      { name: "Pancetta or bacon, diced", amount: "150g" },
      { name: "Large eggs", amount: "3 eggs" },
      { name: "Egg yolks", amount: "2 yolks" },
      { name: "Pecorino Romano, finely grated", amount: "80g" },
      { name: "Parmesan, finely grated", amount: "30g" },
      { name: "Garlic clove", amount: "1 clove" },
      { name: "Freshly cracked black pepper", amount: "2 tsp" },
      { name: "Salt for pasta water", amount: "1 tbsp" },
    ],
    steps: [
      "Whisk eggs, yolks, Pecorino, and Parmesan together in a bowl until smooth. Add 1 tsp cracked black pepper and set aside.",
      "Cook spaghetti in heavily salted boiling water until 1 minute before al dente; reserve 1 cup of pasta water before draining.",
      "Fry pancetta with the garlic clove in a skillet over medium heat until crispy, about 5 minutes. Remove garlic and discard.",
      "Working quickly off the heat, add drained pasta to the pancetta pan and toss to coat in the rendered fat.",
      "Pour egg mixture over pasta and toss vigorously, adding pasta water a splash at a time to create a glossy, creamy sauce — the residual heat cooks the eggs without scrambling them.",
      "Plate immediately and finish with the remaining black pepper and extra grated Pecorino.",
    ],
    nutrition: {
      calories: 640,
      protein: "30g",
      carbs: "72g",
      fat: "26g",
    },
  },
  {
    id: "6",
    title: "Korean Bulgogi Beef Bowl",
    description:
      "Tender slices of beef marinated in soy, sesame, and pear, then caramelized in a hot skillet. A Korean BBQ classic served over steamed rice with quick pickled vegetables.",
    image:
      "https://images.unsplash.com/photo-1707897687558-22bdecb2e1c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZWxpY2lvdXMlMjBhc2lhbiUyMGZvb2QlMjBib3dsfGVufDF8fHx8MTc3MzAzNjMzOXww&ixlib=rb-4.1.0&q=80&w=1080",
    time: "25 min",
    cost: "$11",
    servings: 2,
    category: "Korean",
    tag: "Smoky",
    ingredients: [
      { name: "Beef sirloin, thinly sliced", amount: "250g" },
      { name: "Soy sauce", amount: "3 tbsp" },
      { name: "Asian pear or kiwi, grated", amount: "2 tbsp" },
      { name: "Sesame oil", amount: "1 tbsp" },
      { name: "Brown sugar", amount: "1 tbsp" },
      { name: "Garlic cloves, minced", amount: "3 cloves" },
      { name: "Fresh ginger, grated", amount: "1 tsp" },
      { name: "Green onions, chopped", amount: "3 stalks" },
      { name: "Sesame seeds", amount: "1 tsp" },
      { name: "Cooked white rice", amount: "2 cups" },
    ],
    steps: [
      "Combine soy sauce, grated pear, sesame oil, brown sugar, garlic, and ginger to make the marinade.",
      "Toss sliced beef in the marinade and let sit for at least 10 minutes (30 minutes in the fridge is better).",
      "Heat a cast-iron skillet or grill pan over high heat until very hot — almost smoking.",
      "Cook beef in a single layer for 2 minutes without touching, then flip and cook another 1–2 minutes until caramelized edges form. Work in batches to avoid steaming.",
      "Let beef rest for 1 minute before serving over steamed rice.",
      "Top with green onions, sesame seeds, and a drizzle of extra sesame oil.",
    ],
    nutrition: {
      calories: 560,
      protein: "35g",
      carbs: "60g",
      fat: "18g",
    },
  },
  {
    id: "7",
    title: "Tonkotsu-Style Quick Ramen",
    description:
      "A rich, creamy ramen broth built in minutes from pantry staples — pork miso paste, sesame, and soy — topped with a soft-boiled egg and crispy nori.",
    image:
      "https://images.unsplash.com/photo-1673824085288-ea05299e4f72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMHN0dWRlbnQlMjBjb29raW5nJTIwcmFtZW4lMjBub29kbGVzfGVufDF8fHx8MTc3MzAzNjMzOHww&ixlib=rb-4.1.0&q=80&w=1080",
    time: "10 min",
    cost: "$5",
    servings: 1,
    category: "Japanese",
    tag: "Umami",
    ingredients: [
      { name: "Instant ramen noodles (discard flavor packet)", amount: "1 pack" },
      { name: "Chicken or vegetable broth", amount: "2 cups" },
      { name: "White miso paste", amount: "1 tbsp" },
      { name: "Soy sauce", amount: "1 tbsp" },
      { name: "Sesame oil", amount: "1 tsp" },
      { name: "Garlic clove, minced", amount: "1 clove" },
      { name: "Large egg", amount: "1 egg" },
      { name: "Green onion, sliced", amount: "1 stalk" },
      { name: "Nori sheet", amount: "1 sheet" },
      { name: "Corn kernels (optional)", amount: "2 tbsp" },
    ],
    steps: [
      "Bring a small pot of water to boil. Gently lower in the egg and cook for exactly 6.5 minutes, then transfer to ice water for 2 minutes. Peel and halve.",
      "In a separate saucepan, sauté minced garlic in a drop of sesame oil for 30 seconds over medium heat.",
      "Add broth and bring to a gentle simmer. Whisk in miso paste until fully dissolved, then stir in soy sauce and sesame oil.",
      "Cook ramen noodles according to package directions (about 2 minutes), then drain.",
      "Pour hot broth into a bowl, add noodles, and arrange the soft-boiled egg, corn, and torn nori on top.",
      "Finish with sliced green onion and a few drops of chili oil if desired.",
    ],
    nutrition: {
      calories: 430,
      protein: "18g",
      carbs: "55g",
      fat: "16g",
    },
  },
  {
    id: "8",
    title: "Mediterranean Chickpea & Feta Salad",
    description:
      "A vibrant, no-cook salad bursting with roasted chickpeas, juicy tomatoes, cucumber, Kalamata olives, and creamy feta tossed in a bright lemon-herb dressing.",
    image:
      "https://images.unsplash.com/photo-1757332914538-4b5ed7ae95e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xvcmZ1bCUyMGZvb2QlMjBpbmdyZWRpZW50cyUyMHZlZ2V0YWJsZXMlMjBjb29raW5nfGVufDF8fHx8MTc3MzAzNjMzOXww&ixlib=rb-4.1.0&q=80&w=1080",
    time: "35 min",
    cost: "$12",
    servings: 4,
    category: "Mediterranean",
    tag: "Fresh",
    ingredients: [
      { name: "Canned chickpeas, drained and dried", amount: "1 can (400g)" },
      { name: "Cherry tomatoes, halved", amount: "1 cup" },
      { name: "Cucumber, diced", amount: "1 large" },
      { name: "Kalamata olives, halved", amount: "½ cup" },
      { name: "Feta cheese, crumbled", amount: "100g" },
      { name: "Red onion, thinly sliced", amount: "¼ onion" },
      { name: "Fresh parsley, chopped", amount: "¼ cup" },
      { name: "Olive oil", amount: "3 tbsp" },
      { name: "Lemon juice", amount: "2 tbsp" },
      { name: "Dried oregano", amount: "1 tsp" },
      { name: "Salt and black pepper", amount: "to taste" },
    ],
    steps: [
      "Preheat oven to 400°F (200°C). Toss dried chickpeas with 1 tbsp olive oil, salt, pepper, and ½ tsp oregano on a baking sheet.",
      "Roast chickpeas for 25–30 minutes, shaking the pan halfway, until golden and crispy.",
      "While chickpeas roast, whisk together remaining olive oil, lemon juice, oregano, salt, and pepper to make the dressing.",
      "Combine cherry tomatoes, cucumber, olives, red onion, and parsley in a large bowl.",
      "Let roasted chickpeas cool for 5 minutes, then add them to the salad along with crumbled feta.",
      "Pour dressing over the salad and toss gently to combine. Taste and adjust seasoning before serving.",
    ],
    nutrition: {
      calories: 340,
      protein: "13g",
      carbs: "38g",
      fat: "17g",
    },
  },
];

export default { recipes };
